sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

scala:
  - 2.11.7

jdk:
  - oraclejdk8

install: ./bin/build-deps.sh

before_cache:
  - find $HOME/.sbt -name "*.lock" | tee /dev/stderr | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | tee /dev/stderr | xargs rm
